### ISSUE TITLE
MVP feedback on metrics page

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#12]
This issue tracks testing feedback relating to the metrics page.

1. Could we make this environment dropdown selector the same one as currently used in the logs page?
2. When mixing and matching various metrics sometimes the graph doesn't update.
3. Should we have a way to remove a metric from the graph that's outside of the "available metrics navigation?" It's a little bit awkward that you have to remember where a metric was added and then go back there to unselect the checkbox.
4. Mixing metrics with different units is weird. e.g. "Invocations" and "ReadDurationMS". I'm wondering if for MVP if we should just require the units to be the same? Suggest optimizing for minimizing developer time and we can revisit later.
5. Selecting the database metrics shows an empty graph. For the same time range, the metric graphs we include on the database page do have data, so i know there's metric data there.
6. Same as 5 but for datastore metrics.

**Comment by carensdorf** [comment]
1. Sure.
2. Let me try and reproduce and investigate.
3. Yeah I have some ideas.
4. I agree. However, one option is that we just leave it as is and let customers decide what makes sense to put together. If its easy to remove previously selected metrics i.e. the third item above then it shouldn't be too difficult for customers to mix and match metrics that go well together. Otherwise, it would be a bit of logic to determine what was selected first and then give an error when customers try and select something that doesn't match or disable the checkmark with some kind of explanation near it so customers understand why they can't click something anymore
5. Good catch will investigate.
6. Same.
