### ISSUE TITLE
MVP feedback on selected project page

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#3]
This issue tracks testing feedback relating to the project page once a project is selected by the user.

1. Currently on a mobile browser it is impossible to select the Datastores, Deployments, and Packages tabs. Can we include a horizontal scrollbar when the horizontal width of the full set of tabs exceeds the screen resolution width?

**Comment by carensdorf** [comment]
1. Yes, will make this more mobile-friendly.

**Comment by carensdorf** [comment]
Note: I'm using the "variant = scrollable" for the Material UI tabs component now which allows users to click and drag the tabs horizontally. This may not be obvious to users. Let me know what you think. I currently prefer this approach because it allows the rest of the page to be mobile friendly as well and I can manage the responsive behavior of each component individually which gives a better experience vs a horizontal scroll bar for the whole page.

Let me know if you prefer something different.
