### ISSUE TITLE
MVP feedback on selected service page

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#9]
This issue tracks testing feedback relating to a selected service page once the services tab of a select project is clicked on by the user, and then subsequently the user clicked on a specific service.

1. Could we add a deep link somewhere to the logs page with the project & service auto-filled in for the currently selected service? e.g. perhaps next to API definition and Port?
2. Endpoint health: could we show Healthy as green?
3. On PC my browser(firefox) is rendering this page with an extra vertical scrollbar. It looks like there's the normal vertical scrollbar built into firefox itself, but then there is another vertical scrollbar within the page. The page one doesn't scroll the leftnav & logout dropdown, but the firefox one does. Should we nuke the page one? (having 2 vertical scrollbars next to each other is intuitively confusing to me).
4. The custom time selector for the metrics graphs isn't working.
5. Could we re-label "5xx count" to Error Count for MVP? Are you populating this from metrics scope==service name==Errors currently?
6. On mobile browser the metrics graphs are vertically squished. Any chance we could just nuke the excess vertical whitespace?

**Comment by carensdorf** [comment]
1. Yes, will investigate how to achieve this.
2. Yeah, I have to implement a hook to detect health. Will do that today/tomorrow.
3. Agree, let me investigate how/why the extra scrollbar appears
4. Good catch, will wire that up.
5. Yes, this is errors. Will change to "Error count"
6. Will investigate options on mobile.

**Comment by carensdorf** [comment]
NOTE: for item 6 above, unsure exactly what you meant but removed some unecessary vertical white space under metric labels of previous graphs. However, any more vertical or horizontal manipulation of the graph itself is nearly impossible because ChartJS uses the predefined params of the container to create a HTML Canvas and draw the graphs with vectors. Let me know if you have other thoughts on this or need this to be updated further.
